### ISSUE TITLE
Automated testing is failing on this formula

### ISSUE THREAD

**Issue by myii** [saltstack-formulas/lvm-formula#19]
@noelmcloughlin I run weekly tests of all converted formulas against Salt's `master` branch, as additional QA.  The `lvm-formula` has been passing up until this week:

* https://travis-ci.org/github/myii/lvm-formula/builds/671810026

When it failed this week, I also tested it against `3000.1` as well as `2019.2` but all are failing:

* https://travis-ci.org/github/myii/lvm-formula/builds/676073898
* https://travis-ci.org/github/myii/lvm-formula/builds/676255081

It appears to be the same state failing:

```sls
                 ID: lvm_pv_create_/dev/loop4
           Function: lvm.pv_present
               Name: /dev/loop4
             Result: False
            Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/lvm.py", line 66, in pv_present
                  changes = __salt__['lvm.pvcreate'](name, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/modules/linux_lvm.py", line 255, in pvcreate
                  raise CommandExecutionError(out.get('stderr'))
              salt.exceptions.CommandExecutionError:   WARNING: Failed to connect to lvmetad. Falling back to device scanning.
                Can't open /dev/loop4 exclusively.  Mounted filesystem?
```

Note, this is also causing the `iscsi-formula` testing to fail, since it uses the `lvm-formula` as a dependency.

---

References:

* https://github.com/saltstack/salt/commits/master/salt/modules/linux_lvm.py
* https://github.com/saltstack/salt/commits/master/salt/states/lvm.py
* https://travis-ci.org/github/myii/iscsi-formula/builds/675996548 -- `iscsi-formula` failure

**Comment by noelmcloughlin** [comment]
Hi, @myii I'll have a look at this when I get time.  I think I recall some issue in the past when trying to guess names of the loop devices. Possibly some Docker container parameter changed.  The tests or states may need to be redesigned to remove the guesswork. thanks

**Comment by noelmcloughlin** [comment]
Hi @Myii

For lvm formula, I raised
https://github.com/saltstack-formulas/lvm-formula/pull/20 which hopefully
passes tests in future.

For iscsi formula, there is known issue with Linux kernel requiring a
reboot on Arch/Centos - this seems impossible to fix in Travis:
https://github.com/saltstack-formulas/iscsi-formula/issues/33

**Comment by myii** [comment]
@noelmcloughlin Nice, I'll try to get around to it soon.  Does `iscsi` work for the other platforms, though?

**Comment by noelmcloughlin** [comment]
Yes, I fixed Centos.  Only arch job is failing for iscsi - trying some
things but not promising.

**Comment by noelmcloughlin** [comment]
PRs raised to fix things:
LVM: https://github.com/saltstack-formulas/lvm-formula/pull/20
ISCSI: https://github.com/saltstack-formulas/iscsi-formula/pull/35
